<Project Sdk="Microsoft.NET.Sdk.Web">

	<PropertyGroup>
		<TargetFramework>net9.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<GenerateAssemblyInfo>false</GenerateAssemblyInfo>
		<GenerateTargetFrameworkAttribute>false</GenerateTargetFrameworkAttribute>
	</PropertyGroup>

	<ItemGroup>
		<Content Remove="Controllers\Properties\launchSettings.json" />
		<Content Remove="Controllers\Properties\serviceDependencies.json" />
		<Content Remove="Controllers\Properties\serviceDependencies.local.json" />
	</ItemGroup>

	<ItemGroup>
		<None Include="Controllers\Properties\launchSettings.json" />
		<None Include="Controllers\Properties\serviceDependencies.json" />
		<None Include="Controllers\Properties\serviceDependencies.local.json" />
	</ItemGroup>

	<ItemGroup>
		<!-- Azure Storage packages (KEEP THESE) -->
		<PackageReference Include="Azure.Data.Tables" Version="12.11.0" />
		<PackageReference Include="Azure.Storage.Blobs" Version="12.25.0" />
		<PackageReference Include="Azure.Storage.Files.Shares" Version="12.23.0" />
		<PackageReference Include="Azure.Storage.Queues" Version="12.23.0" />
		<PackageReference Include="Microsoft.AspNetCore.Session" Version="2.3.0" />

		<!-- ASP.NET Core packages (KEEP THESE) -->
		<PackageReference Include="Microsoft.AspNetCore.WebUtilities" Version="9.0.9" />
		<PackageReference Include="Microsoft.Azure.Functions.Worker.Extensions.Storage.Queues" Version="5.5.3" />
		<PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.11" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="9.0.11" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="10.0.0">
		  <PrivateAssets>all</PrivateAssets>
		  <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="Microsoft.Net.Http.Headers" Version="9.0.9" />
		<PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="9.0.0" />
	</ItemGroup>

</Project>